---
title: "Math 312 Project"
author: "Kenneth Straw and Logan Kramer"
github: "https://github.com/loganizer405/MATH312Project"
output: pdf_document
---

# Chi-squared Distribution

```{r}
#Set seed
set.seed(420)

#Set our n to 20 for X1...X20 and alpha to 0.1
n <- 20
alpha <- 0.10
df <- 1
#Mean of a chisq distribution is equal to the degrees of freedom
mu0 <- df

#Set m to 10000 replicates
m <- 10000

p <- numeric(m) #To store p value

#Run our simulation
for(j in 1:m){
  x <- rchisq(n, df)
  ttest <- t.test(x, alternative = "t", mu = mu0)
  p[j] <- ttest$p.value
}

#Print our p.hat 
(p.hat <- mean(p < alpha))
```
# Uniform Distribution

```{r}
#Set seed
set.seed(420)

#Set our n to 20
n <- 20
alpha <- 0.10

#Set m to 10000 replicates
m <- 10000

min <- 0
max <- 2
#Mean of a uniform distribution is equal to (a + b)/2
mu0 <- (min+max)/2

p <- numeric(m) #To store p value

#Run our simulation
for(j in 1:m){
  x <- runif(n, min, max)
  ttest <- t.test(x, alternative = "t", mu = mu0)
  p[j] <- ttest$p.value
}

#Print our p.hat 
(p.hat <- mean(p < alpha))
```

# Exponential Distribution

```{r}
#Set seed
set.seed(420)

#Set our n to 20
n <- 20
alpha <- 0.10

#Set m to 10000 replicates
m <- 10000

rate <- 1
#Mean of a exponential distribution is equal to 1/rate
mu0 <- 1/rate

p <- numeric(m) #To store p value

#Run our simulation
for(j in 1:m){
  x <- rexp(n, rate)
  ttest <- t.test(x, alternative = "t", mu = mu0)
  p[j] <- ttest$p.value
}

#Print our p.hat 
(p.hat <- mean(p < alpha))
```
